#!/usr/bin/env python
"""Re-render the headline slide figures from an EXISTING artifact package
(candidate_trace.csv + selected_circuits.json) without re-running the
experiment or touching any API.

Purpose: apply the slide-ready figure design (fixed method colors, big
fonts, bars + 95% CI + value labels, lower-is-better cues) to an
already-committed run's real data. Only the four comparison figures are
re-rendered -- diagnostics figures that need live circuit objects are left
as generated by the original run.
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from llm_vqc.free_amplitude.main_reporting import (  # noqa: E402
    _apply_slide_style,
    _fig_arm_comparison_summary,
    _fig_best_so_far_rmse,
    _fig_test_rmse_by_arm,
    _fig_validation_rmse_distribution,
)
from llm_vqc.free_amplitude.main_runner import (  # noqa: E402
    MainArmRunOutcome,
    MainCandidateRecord,
)


def _f(value: str):
    return float(value) if value not in ("", "None", None) else None


def load_outcomes(output_dir: Path) -> list[MainArmRunOutcome]:
    selections = json.loads((output_dir / "selected_circuits.json").read_text())
    outcomes: dict[tuple, MainArmRunOutcome] = {}
    for sel in selections:
        key = (sel["seed"], sel["arm"])
        outcomes[key] = MainArmRunOutcome(
            seed=sel["seed"], arm=sel["arm"], task_namespace="",
            n_qubits=sel.get("n_qubits", 0),
            selected_val_rmse=sel.get("selected_val_rmse"),
            protected_test_rmse=sel.get("protected_test_rmse"),
            protected_test_mae=sel.get("protected_test_mae"),
            selected_operations=sel.get("selected_operations"),
            selected_theta=sel.get("selected_theta"),
            selected_candidate_hash=sel.get("selected_candidate_hash"),
            selected_architecture_hash=sel.get("selected_architecture_hash"),
        )
    with (output_dir / "candidate_trace.csv").open() as f:
        for row in csv.DictReader(f):
            key = (int(row["seed"]), row["arm"])
            if key not in outcomes:
                outcomes[key] = MainArmRunOutcome(
                    seed=int(row["seed"]), arm=row["arm"], task_namespace="",
                )
            outcomes[key].candidates.append(
                MainCandidateRecord(
                    seed=int(row["seed"]), arm=row["arm"],
                    proposal_index=int(row["proposal_index"]),
                    proposal_id=row["proposal_id"],
                    operations=json.loads(row["operations"]) if row["operations"] else None,
                    theta=json.loads(row["theta"]) if row["theta"] else None,
                    architecture_hash=row["architecture_hash"] or None,
                    candidate_hash=row["candidate_hash"] or None,
                    valid=row["valid"] == "True",
                    is_duplicate=row["is_duplicate"] == "True",
                    outcome=row["outcome"],
                    train_mse=_f(row["train_mse"]), val_rmse=_f(row["val_rmse"]),
                    val_mae=_f(row["val_mae"]),
                    prediction_mean=_f(row["prediction_mean"]),
                    prediction_std=_f(row["prediction_std"]),
                    prediction_min=_f(row["prediction_min"]),
                    prediction_max=_f(row["prediction_max"]),
                    constant_output=row["constant_output"] == "True",
                    circuit_depth=int(row["circuit_depth"]) if row["circuit_depth"] else None,
                    searched_body_depth=row["searched_body_depth"] or None,
                    searched_body_gate_count=(
                        int(row["searched_body_gate_count"])
                        if row["searched_body_gate_count"] else None
                    ),
                    controlled_gate_count=(
                        int(row["controlled_gate_count"])
                        if row["controlled_gate_count"] else None
                    ),
                    quantum_parameter_count=(
                        int(row["quantum_parameter_count"])
                        if row["quantum_parameter_count"] else None
                    ),
                    parameter_count_in_causal_cone=(
                        int(row["parameter_count_in_causal_cone"])
                        if row["parameter_count_in_causal_cone"] else None
                    ),
                    fraction_in_causal_cone=_f(row["fraction_in_causal_cone"]),
                    best_so_far_val_rmse=_f(row["best_so_far_val_rmse"]),
                    api_latency_seconds=_f(row["api_latency_seconds"]),
                    input_tokens=int(row["input_tokens"]) if row["input_tokens"] else None,
                    output_tokens=int(row["output_tokens"]) if row["output_tokens"] else None,
                )
            )
    return list(outcomes.values())


def main() -> None:
    default_dir = "outputs/free_amplitude_fixed_readout_v1"
    output_dir = Path(sys.argv[1] if len(sys.argv) > 1 else default_dir)
    outcomes = load_outcomes(output_dir)
    _apply_slide_style()
    _fig_arm_comparison_summary(output_dir, outcomes)
    _fig_best_so_far_rmse(output_dir, outcomes)
    _fig_validation_rmse_distribution(output_dir, outcomes)
    _fig_test_rmse_by_arm(output_dir, outcomes)
    print(f"Re-rendered 4 slide figures (PNG+SVG+CSV) under {output_dir}/figures/")


if __name__ == "__main__":
    main()
